org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.2
loom_version=1.15.5

mod_version=1.0.0
maven_group=com.example

fabric_api_version=0.116.12+1.21.1
implementation 'com.google.code.gson:gson:2.10.1'